### ISSUE TITLE
Subsecond node-receipt timestamp

### ISSUE THREAD

**Issue by Mitchellpkt** [Mitchellpkt/monero_archival_project#17]
When each copy of a block is received (perhaps multiple copies from multiple nodes), record the node receipt timestamp to milliseconds.

This enables study of latency. What's the timing on the shortest route for a txn/block to arrive at MAP node? What's the timing on the longest route? What is the scale of the time difference? milliseconds? seconds?

**Comment by neptuneresearch** [comment]
Consolidating to https://github.com/Mitchellpkt/monero_archival_project/issues/7.
