### ISSUE TITLE
Use DataFrame.loc instead of multiple indexing to assign values.

### ISSUE THREAD

**Issue by neffmallon** [Mitchellpkt/monero_archival_project#20]
There are currently multiple warnings raised for using multiple indexing to assign values. This is bad practice, see [Pandas docs](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy).

**Comment by Mitchellpkt** [comment]
Ah I tried to fix that, but was getting errors (I see now, from your example, that I was indicating the field incorrectly). Many thanks!
