### ISSUE TITLE
Installing Grafana

### ISSUE THREAD

**Issue by serhack** [Mitchellpkt/monero_archival_project#25]
This issue will track my work in order to install Grafana in one VPS for MAP Project.

- [x] Install Grafana on MAP-GRAFANA machine.

- [x] Install InfluxDB

- [x] Pointing all the CollectD to the InfluxDB

- [x] Create the dashboard "Nodes" and the row. Each row will be called as the hostname of VPS

**Comment by Mitchellpkt** [comment]
:100: 

This will be beautiful!
