### ISSUE TITLE
G_LIBC Upgrade

### ISSUE THREAD

**Issue by serhack** [Mitchellpkt/monero_archival_project#32]
Debian 9 has G_LIBC (package known as libc6-dev) preinstalled version 2.24 . 

To upgrade you need to follow these passages. Warning: if you run commands and you don't know what they do, please don't try to upgrade G_LIBC! 

1. Open with any editor the `/etc/apt/sources.list`

2. Add the following line `deb http://ftp.us.debian.org/debian sid main`

3. Run `apt-get update`

4. Let's upgrade LIBC! Run `apt-get install libc6-dev` and then wait...

5. Reopen `/etc/apt/sources.list` and **comment** (with "#") the line you wrote in the step 2.

6. Enjoy!

NEVER NEVER run a `apt-get upgrade` or `apt-get full-upgrade` while you are touching `/etc/apt/sources.list` . If you upgrade all the packages to "sid", the system can become unstable.

**Comment by neptuneresearch** [comment]
Great work :) I've followed this several times now. 

I added this to the monerod-archive README.
