### ISSUE TITLE
Node-receipt timestamp

### ISSUE THREAD

**Issue by Mitchellpkt** [Mitchellpkt/monero_archival_project#7]
The "timestamp" included in the block by the miner could be spoofed, inaccurate, or not updated.

Should record two fields:
-  miner-reported timestamp (MRT)
-  node-received timestamp (NRT)

**Comment by Mitchellpkt** [comment]
Curious to see how much difference there is between the two versions. Unknown to date, afaik

**Comment by Mitchellpkt** [comment]
Also, will check to see whether the elbow in the discovery time disappears on histogram of node-received timestamp differences.

**Comment by neptuneresearch** [comment]
Copy from #17:

## Subsecond node-receipt timestamp

When each copy of a block is received (perhaps multiple copies from multiple nodes), record the node receipt timestamp to milliseconds.

This enables study of latency. What's the timing on the shortest route for a txn/block to arrive at MAP node? What's the timing on the longest route? What is the scale of the time difference? milliseconds? seconds?

**Comment by Mitchellpkt** [comment]
I think this can be closed when you push `monerod-archive-v6t` to your repo, the NRT seems to work fine.

**Comment by Mitchellpkt** [comment]
Closed. Thanks @neptuneresearch
